version: '3.3'
volumes:
  pg_data:
  foodgram_static:
  foodgram_media:
  foodgram_frontend:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

  backend:
    image: redc0mrade/foodgram_backend
    volumes:
      - foodgram_static:/app/static_backend/
      - foodgram_media:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  frontend:
    image: redc0mrade/foodgram_frontend
    volumes:
     - ../frontend/:/app/result_build/

  gateway:
    image: redc0mrade/foodgram_gateway
    ports:
      - "7000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static:/var/html/static_backend/
      - foodgram_media:/var/html/media/
    depends_on:
      - backend
    restart: always