version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - foodgram_db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: redc0mrade/foodgram_backend:latest
    restart: always
    volumes:
      - foodgram_static:/app/static_backend/
      - foodgram_media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: redc0mrade/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "7000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static:/var/html/static_backend/
      - foodgram_media:/var/html/media/
    depends_on:
      - backend
    restart: always

volumes:
  foodgram_static:
  foodgram_media:
  foodgram_db:
  foodgram_frontend: